apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo
  labels:
    app: fastapi-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-todo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fastapi-todo
    spec:
      containers:
        - name: fastapi-todo
          image: fastapi-todo:v1.0.0  # Use specific version tag instead of latest
          imagePullPolicy: Never   # Use 'Never' for local Docker images
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health  # Consider implementing a lightweight health endpoint
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health  # Consider implementing a lightweight health endpoint
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: fastapi-config
            - secretRef:
                name: fastapi-secret