apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dG9kb2RiaiA=              # base64 of "tododb"
  POSTGRES_USER: ZGV2dXNlcg==            # base64 of "devuser"
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=    # base64 of "supersecret"
